# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-27 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatrimonyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20)),
                ('mother_name', models.CharField(max_length=20)),
                ('sal', models.IntegerField()),
                ('mobile', models.BigIntegerField(unique=True)),
                ('color', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password1', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('dob', models.DateField(max_length=20)),
                ('height', models.FloatField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('locations', multiselectfield.db.fields.MultiSelectField(choices=[('Hyd', 'Hyderabad'), ('Bang', 'Bangalore'), ('Chen', 'Chennai'), ('Mum', 'Mumbai')], max_length=20)),
                ('jobtype', multiselectfield.db.fields.MultiSelectField(choices=[('Govt', 'Govt Job'), ('S/W', 'Software'), ('Trainers', 'Teachers'), ('Doctor', 'Doctors'), ('Police', 'Police')], max_length=20)),
                ('looking_for', models.CharField(choices=[('Male', 'GROOM'), ('Female', 'BRIDE')], max_length=20)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
