# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-01 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0002_auto_20180801_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gno', models.IntegerField()),
                ('gname', models.CharField(max_length=20)),
                ('profile', models.ManyToManyField(to='regapp.Profile')),
            ],
        ),
    ]
